"""Add segmentation fields to multimodal results

Revision ID: 117a8faedcf4
Revises: 5accd9d1a8d2
Create Date: 2026-05-11 01:41:02.980844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117a8faedcf4'
down_revision = '5accd9d1a8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultrasound_segmentation_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ultrasound_segmentation_public_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('ultrasound_segmentation_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mammogram_segmentation_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('mammogram_segmentation_public_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('mammogram_segmentation_confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_results', schema=None) as batch_op:
        batch_op.drop_column('mammogram_segmentation_confidence')
        batch_op.drop_column('mammogram_segmentation_public_id')
        batch_op.drop_column('mammogram_segmentation_url')
        batch_op.drop_column('ultrasound_segmentation_confidence')
        batch_op.drop_column('ultrasound_segmentation_public_id')
        batch_op.drop_column('ultrasound_segmentation_url')

    # ### end Alembic commands ###
