"""staging

Revision ID: 20488f661da8
Revises: fec083ba6e12
Create Date: 2026-05-10 01:04:55.581484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20488f661da8'
down_revision = 'fec083ba6e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stagings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('tumor_size', sa.Float(), nullable=True),
    sa.Column('no_primary_tumour', sa.Boolean(), nullable=False),
    sa.Column('lymphadenopathy', sa.Float(), nullable=True),
    sa.Column('metastatic', sa.Integer(), nullable=True),
    sa.Column('skin_nipple', sa.Integer(), nullable=True),
    sa.Column('pec_chest', sa.Integer(), nullable=True),
    sa.Column('er', sa.Integer(), nullable=True),
    sa.Column('pr', sa.Integer(), nullable=True),
    sa.Column('her2', sa.Integer(), nullable=True),
    sa.Column('histologic_grade', sa.Integer(), nullable=True),
    sa.Column('cT_stage', sa.String(length=10), nullable=True),
    sa.Column('cN_stage', sa.String(length=10), nullable=True),
    sa.Column('cM_stage', sa.String(length=5), nullable=True),
    sa.Column('anatomic_stage', sa.String(length=10), nullable=True),
    sa.Column('prognostic_stage', sa.String(length=10), nullable=True),
    sa.Column('result_label', sa.Text(), nullable=False),
    sa.Column('molecular_subtype', sa.String(length=30), nullable=True),
    sa.Column('detection_scan_id', sa.UUID(), nullable=True),
    sa.Column('mri_scan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detection_scan_id'], ['detection_scans.scan_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mri_scan_id'], ['mri_scans.scan_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stagings')
    # ### end Alembic commands ###
