"""add mri scans table

Revision ID: 48ac6b5183f2
Revises: 5bd395d4d967
Create Date: 2026-04-27 03:34:16.028437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ac6b5183f2'
down_revision = '5bd395d4d967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mri_scans',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('acq0_url', sa.String(length=500), nullable=False),
    sa.Column('acq0_public_id', sa.String(length=300), nullable=False),
    sa.Column('acq1_url', sa.String(length=500), nullable=True),
    sa.Column('acq1_public_id', sa.String(length=300), nullable=True),
    sa.Column('acq2_url', sa.String(length=500), nullable=False),
    sa.Column('acq2_public_id', sa.String(length=300), nullable=False),
    sa.Column('t_stage', sa.Enum('T1mi', 'T1a', 'T1b', 'T1c', 'T2', 'T3', name='tumorstage'), nullable=True),
    sa.Column('size_cm', sa.Float(), nullable=True),
    sa.Column('volume_cc', sa.Float(), nullable=True),
    sa.Column('segmentation_consistency', sa.Float(), nullable=True),
    sa.Column('uncertainty_mean', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mri_scans')
    # ### end Alembic commands ###
