"""multimodal1

Revision ID: 5accd9d1a8d2
Revises: 816eee572089
Create Date: 2026-05-11 01:21:54.098390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5accd9d1a8d2'
down_revision = '816eee572089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultrasound_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ultrasound_image_public_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('mammogram_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('mammogram_image_public_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('shared_with_doctor', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('mental_health_mode', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_results', schema=None) as batch_op:
        batch_op.drop_column('mental_health_mode')
        batch_op.drop_column('shared_with_doctor')
        batch_op.drop_column('mammogram_image_public_id')
        batch_op.drop_column('mammogram_image_url')
        batch_op.drop_column('ultrasound_image_public_id')
        batch_op.drop_column('ultrasound_image_url')

    # ### end Alembic commands ###
