"""update scans table with segmentation

Revision ID: 5bd395d4d967
Revises: 00f35a588b9f
Create Date: 2026-04-24 06:30:13.565926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bd395d4d967'
down_revision = '00f35a588b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_scans',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('image_type', sa.Enum('ultrasound', 'mammogram', name='detectionimagetype'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_public_id', sa.String(length=300), nullable=False),
    sa.Column('prediction', sa.Enum('benign', 'malignant', 'normal', name='detectionprediction'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prob_benign', sa.Float(), nullable=False),
    sa.Column('prob_malignant', sa.Float(), nullable=False),
    sa.Column('prob_normal', sa.Float(), nullable=False),
    sa.Column('segmentation_url', sa.String(length=500), nullable=True),
    sa.Column('segmentation_public_id', sa.String(length=300), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('shared_with_doctor', sa.Boolean(), nullable=False),
    sa.Column('mental_health_mode', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('multimodal_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('ultrasound_scan_id', sa.UUID(), nullable=False),
    sa.Column('mammogram_scan_id', sa.UUID(), nullable=False),
    sa.Column('prediction', sa.Enum('benign', 'malignant', 'normal', name='detectionprediction'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prob_benign', sa.Float(), nullable=True),
    sa.Column('prob_malignant', sa.Float(), nullable=True),
    sa.Column('prob_normal', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mammogram_scan_id'], ['detection_scans.scan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ultrasound_scan_id'], ['detection_scans.scan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_type', postgresql.ENUM('ultrasound', 'mammogram', name='imagetype'), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('image_public_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('prediction', postgresql.ENUM('benign', 'malignant', 'normal', name='predictionclass'), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prob_benign', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prob_malignant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prob_normal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], name=op.f('scans_patient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id', name=op.f('scans_pkey'))
    )
    op.drop_table('multimodal_results')
    op.drop_table('detection_scans')
    # ### end Alembic commands ###
