"""multimodal

Revision ID: 816eee572089
Revises: 20488f661da8
Create Date: 2026-05-11 01:17:48.843476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816eee572089'
down_revision = '20488f661da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_results', schema=None) as batch_op:
        batch_op.alter_column('ultrasound_scan_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('mammogram_scan_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_results', schema=None) as batch_op:
        batch_op.alter_column('mammogram_scan_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('ultrasound_scan_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
