"""add consent fields to patients

Revision ID: bcf2e6f3a7a8
Revises: 77bd625daafb
Create Date: 2026-05-01 15:50:40.657100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf2e6f3a7a8'
down_revision = '77bd625daafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_given_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('consent_given_at')

    # ### end Alembic commands ###
