"""mri

Revision ID: d101397b8df6
Revises: cf919988280d
Create Date: 2026-05-16 08:14:11.315254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd101397b8df6'
down_revision = 'cf919988280d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('documents_embedding_idx'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')

    op.drop_table('documents')
    with op.batch_alter_table('mri_scans', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('error_msg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mri_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='scanstatus'), autoincrement=False, nullable=False))

    op.create_table('documents',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('documents_embedding_idx'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###
