"""add mri scans table

Revision ID: fbebec0e8acb
Revises: 48ac6b5183f2
Create Date: 2026-04-27 21:18:13.880187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbebec0e8acb'
down_revision = '48ac6b5183f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mri_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acq0_storage_path', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('acq1_storage_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('acq2_storage_path', sa.String(length=300), nullable=False))
        batch_op.drop_column('acq1_public_id')
        batch_op.drop_column('acq0_public_id')
        batch_op.drop_column('acq2_public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mri_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acq2_public_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('acq0_public_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('acq1_public_id', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_column('acq2_storage_path')
        batch_op.drop_column('acq1_storage_path')
        batch_op.drop_column('acq0_storage_path')

    # ### end Alembic commands ###
